joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

yb_arm_joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: yb_arm_joint_1
  pid: {p: 2.0, i: 0.5, d: 0.5}

yb_arm_joint_2_position_controller:
  type: effort_controllers/JointPositionController
  joint: yb_arm_joint_2
  pid: {p: 15.0, i: 0.5, d: 0.5}

yb_arm_joint_3_position_controller:
  type: effort_controllers/JointPositionController
  joint: yb_arm_joint_3
  pid: {p: 2.0, i: 0.5, d: 0.5}

yb_arm_joint_4_position_controller:
  type: effort_controllers/JointPositionController
  joint: yb_arm_joint_4
  pid: {p: 2.0, i: 0.5, d: 0.5}

yb_arm_joint_5_position_controller:
  type: effort_controllers/JointPositionController
  joint: yb_arm_joint_5
  pid: {p: 2.0, i: 0.5, d: 0.5}